Updated dependencies and compilied for cuba 6.10
mariodavid/cuba-component-taggable pull request #5
Opened 2018-12-29 17:29 UTC by utrost

Used MySQL as Database, updated dependencies for cuba 6.10

2018-12-29 20:18 UTC, mariodavid commented
hi,

thanks for contribution! Really appreciate it...

Will look into the changes and give you feedback before we merge it.

2018-12-29 20:23 UTC, mariodavid requested changes
looks great! please remove not needed files, push again and then we merge & release...

2018-12-29 20:23 UTC, mariodavid commented on build.gradle
> +def mysql = 'mysql:mysql-connector-java:5.1.46'
can you switch back to HSQLDB for later development? Doing it via studio does not require you to change all the code snippets. thanks!

2018-12-29 20:23 UTC, mariodavid commented on modules/core/db/update/mysql/18/181229-0-dropCustomer.sql
> +rename table ddct_customer to DDCT_CUSTOMER__U47525 ;
you can remove those. Those are internal test classes - that should not be generated. Can be deleted.

2018-12-29 20:23 UTC, mariodavid commented on modules/core/db/update/mysql/18/181229-0-dropCustomer_DropScript.sql
> +drop table if exists DDCT_CUSTOMER__U47525 cascade ;
you can remove those. Those are internal test classes - that should not be generated. File can be deleted.

2018-12-29 20:23 UTC, mariodavid commented on modules/core/db/update/mysql/18/181229-0-dropTagTest.sql
> +rename table ddct_tag_test to DDCT_TAG_TEST__U44381 ;
you can remove those. Those are internal test classes - that should not be generated. File can be deleted.

2018-12-29 20:23 UTC, mariodavid commented on modules/core/db/update/mysql/18/181229-1-createCustomer.sql
> +create table DDCT_CUSTOMER (
you can remove those. Those are internal test classes - that should not be generated. File can be deleted.

2018-12-29 20:23 UTC, mariodavid commented on modules/core/db/update/mysql/18/181229-0-dropTagTest_DropScript.sql
> +drop table if exists DDCT_TAG_TEST__U44381 cascade ;
you can remove those. Those are internal test classes - that should not be generated. File can be deleted.

2018-12-29 20:23 UTC, mariodavid commented on modules/core/db/update/mysql/18/181229-1-createTagTest.sql
> +create table DDCT_TAG_TEST (
Seems to be your internal test class - right? should be deleted before merging

2018-12-29 20:23 UTC, mariodavid commented on modules/core/db/update/mysql/18/181229-2-updateTagging.sql
> +alter table DDCT_TAGGING add column CUSTOMER_ID varchar(32) ;
you can remove those. Those are internal test classes - that should not be generated. File can be deleted.

2018-12-29 20:23 UTC, mariodavid commented on modules/core/db/update/mysql/18/181229-2-updateTagging01.sql
> +alter table DDCT_TAGGING add constraint FK_DDCT_TAGGING_ON_CUSTOMER foreign key (CUSTOMER_ID) references DDCT_CUSTOMER(ID);
you can remove those. Those are internal test classes - that should not be generated. File can be deleted.

2018-12-29 20:23 UTC, mariodavid commented on modules/core/db/update/mysql/18/181229-2-updateTagging02.sql
> +update DDCT_TAGGING set DTYPE = 'ddct$Tagging' where DTYPE is null ;
you can remove those. Those are internal test classes - that should not be generated. File can be deleted.

2018-12-29 20:23 UTC, mariodavid commented on modules/core/db/update/mysql/18/181229-2-updateTagging03.sql
> +alter table DDCT_TAGGING change column DTYPE DTYPE__U80164 varchar(100)^
you can remove those. Those are internal test classes - that should not be generated. File can be deleted.

2018-12-29 20:23 UTC, mariodavid commented on modules/core/db/update/mysql/18/181229-2-updateTagging03_DropScript.sql
> +alter table DDCT_TAGGING drop column CUSTOMER_ID__U15937 cascade ;
you can remove those. Those are internal test classes - that should not be generated. File can be deleted.

2018-12-29 20:23 UTC, mariodavid commented on modules/web/src/de/diedavids/cuba/taggable/web/messages.properties
> +menu-config.ddct$TagTest.browse = Tag Tests
Seems to be your internal test class - right? should be deleted before merging

2018-12-30 12:02 UTC, utrost commented
Removed Test data, set HSQLDB as default again.

2018-12-30 17:40 UTC, mariodavid approved these changes

2018-12-30 17:50 UTC, mariodavid commented
thanks for your contribution.

I'll merge it and release 0.3.0 with 6.10 support and MySQL support as well.

If you want you can continue with the attachable addon.

Bye

2018-12-30 17:52 UTC, merged